const BYTE = 1024;
export const MAX_IMAGE_SIZE = 15;
export const MAX_IMAGE_SIZE_IN_MEGA_BYTES = MAX_IMAGE_SIZE * BYTE * BYTE;
export const MAX_IMAGE_SIZE_FORMATTED =
  MAX_IMAGE_SIZE_IN_MEGA_BYTES / BYTE / BYTE;
